/*
 *  @ Daniel Rakovský
 */
package com.mycompany.ticketportal;

import static com.mycompany.ticketportal.GuiHandler.createAdminMainMenu;
import static com.mycompany.ticketportal.Ledger.customerArrayList;
import static com.mycompany.ticketportal.Ledger.privateCustomerArrayList;
import static com.mycompany.ticketportal.Ledger.soldTicketArrayList;
import static com.mycompany.ticketportal.Ledger.ticketArrayList;
import static com.mycompany.ticketportal.TicketPortal.logedInCustomer;
import java.util.ArrayList;

/**
 *
 * @author Daniel
 * soldTicketArrayList
 */
public class ViewReservationWindow extends javax.swing.JFrame {
    
    public void fillTable(){
    ArrayList<Ticket> ticketsFromCarts = getTicketsFromCarts();

    for(int i = 0; i< soldTicketArrayList.size(); i++){

        String origin  = soldTicketArrayList.get(i).origin;
        String destination = soldTicketArrayList.get(i).destination;
        String price = String.valueOf(soldTicketArrayList.get(i).price);
        String idString = String.valueOf(soldTicketArrayList.get(i).idTicket);
        int positionCustomer = soldTicketArrayList.get(i).owner.idCustomer;
        String loginCustomer = privateCustomerArrayList.get(positionCustomer).login;
        
        
        ticketsTable.setValueAt(origin, i, 0);
        ticketsTable.setValueAt(destination, i, 1);
        ticketsTable.setValueAt(price, i, 2);
        ticketsTable.setValueAt(idString, i, 3);
        ticketsTable.setValueAt(loginCustomer, i, 4);
        ticketsTable.setValueAt("PAID", i, 5);
        
        //displayTotalPrice();
    }
    
    if(ticketsFromCarts!=null){
        int size = soldTicketArrayList.size();
        for(int i = 0; i < ticketsFromCarts.size(); i++){
            String origin  = ticketsFromCarts.get(i).origin;
            String destination = ticketsFromCarts.get(i).destination;
            String price = String.valueOf(ticketsFromCarts.get(i).price);
            String idString = String.valueOf(ticketsFromCarts.get(i).idTicket);
            int positionCustomer = ticketsFromCarts.get(i).owner.idCustomer;
            String loginCustomer = privateCustomerArrayList.get(positionCustomer).login;
        
        
            ticketsTable.setValueAt(origin, i + size, 0);
            ticketsTable.setValueAt(destination, i + size, 1);
            ticketsTable.setValueAt(price, i + size, 2);
            ticketsTable.setValueAt(idString, i + size, 3);
            ticketsTable.setValueAt(loginCustomer, i + size, 4);
            ticketsTable.setValueAt("UNPAID", i + size, 5);
        }
    }
    
    }
    
    public static ArrayList<Ticket> getTicketsFromCarts(){
        ArrayList<Ticket> ticketsFromCarts = new ArrayList<>();
        
        for(int i = 0; i < customerArrayList.size(); i++){
            Customer c = customerArrayList.get(i);
                if(!c.customerCart.isEmpty()){
                    for(int j = 0; j< c.customerCart.size(); j++){
                        ticketsFromCarts.add(c.customerCart.get(j));
                        System.out.println("ID: " + c.customerCart.get(j).idTicket);
                    }          
                }  
        }


        return ticketsFromCarts;
    
    }
    /*        
    public void displayTotalPrice(){
        int price = 0;
        
        for(int i = 0; i< logedInCustomer.customerCart.size(); i++){
            price = logedInCustomer.customerCart.get(i).price + price;
        }
        totalLabel.setText("Total " + String.valueOf(price) + " " + "$");
    
    }*/

    /**
     * Creates new form ViewReservationWindow
     */
    public ViewReservationWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ticketsTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ticketsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Origin", "Destination", "Price", "ID Ticket", "Customer", "Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ticketsTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(ticketsTable);
        ticketsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(backButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        createAdminMainMenu();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReservationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReservationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReservationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReservationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReservationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ticketsTable;
    // End of variables declaration//GEN-END:variables
}
